# Generated by Django 4.2.1 on 2023-05-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('text_message', models.TextField()),
                ('client_filter_operator_code', models.CharField(max_length=10)),
                ('client_filter_tag', models.CharField(max_length=50)),
            ],
        ),
    ]
